Refacto/ajoute appel api simulateur et autres erreurs de tests Storybook
betagouv/anssi-nis2 pull request #121
Opened 2024-04-03 16:42 UTC by GalloIT

### Contexte

Des tests Storybook sont en erreur sur le nouveau parcours:

- API pour sauvegarde des résultats non appelée
- Erreur de texte de la tranche employés moyenne dans l'étape taille (**49** au lieu de **249**)
- Suppression des parcours publics qui ne sont plus compatibles avec le nouveau modèle
- Correction des conditions pour les sous-secteurs autres vers résultat (le secteur correspondant au sous-secteur est présent)
- Correction des listes d'activités bloquant le bouton suivant lorsqu'un secteur/sous-secteur "autre" était coché

Améliorations du code :
- Ajout d'un typage fort sur reducer undo
- Utilisation de pattern matching dans `reducerQuestionnaire` pour éviter les imbrications de plus de 2 niveaux de conditions
- Simplifications des appels en passant de l'impératif au déclaratif
- Inversion des paramètres `estParmis` (data as last param)

2024-04-03 18:03 UTC, CadiChris requested changes
Merci pour ces ajouts ! On arrive à qqch de bien abouti. 

Retrouvons-nous le plus tôt possible pour discuter des derniers points ouverts.

2024-04-03 18:03 UTC, CadiChris commented on anssi-nis2-ui/test/questionnaire/reducerQuestionnaire.spec.ts
> +        valideSecteursActivite(["autreSecteurActivite", "fabrication"]),
Je ne comprends pas l'ajout de `fabrication` ici. L'intitulé du test parle de « autre » pour secteur et sous-secteur. Je rate qqch ?

2024-04-03 18:03 UTC, CadiChris commented on anssi-nis2-ui/test/questionnaire/reducerUndo.spec.ts
Cf. commentaire sur le découplage des reducers encore une fois. 
Je préfère brancher les tests sur un reducer « bateau » qui n'a rien à voir avec le questionnaire.

2024-04-04 06:25 UTC, GalloIT commented on anssi-nis2-ui/src/Components/Simulateur/Questionnaire.tsx
> +        envoieDonneesFormulaire,
Si on fait cela, elle est exécutée au rendering. En strict mode, en dev, ça fait un double appel.

2024-04-04 06:25 UTC, GalloIT commented on anssi-nis2-ui/src/questionnaire/actions.ts
> +  | ActionUndo
Oui, je comprends la remarque. Ce sont leurs types qui sont couplés : on pourrait remettre ce type dans l'autre, en effet

2024-04-04 06:27 UTC, GalloIT commented on anssi-nis2-ui/src/questionnaire/quiSupporteUndo.ts
> +type AvecUndo<TEtat extends EtatQuestionnaire> = {
Aucun soucis pour revenir en arrière.

2024-04-04 06:27 UTC, GalloIT commented on anssi-nis2-ui/src/questionnaire/reducerQuestionnaire.ts
> +  ...detailsQuestionnaire,
Oui, je l'ai fait intentionnellement au début, pour effectuer les changements et garder la main sur l'état. OK pour remettre

2024-04-04 06:28 UTC, GalloIT commented on anssi-nis2-ui/src/questionnaire/selecteursQuestionnaire.ts
> +    .filter((s) => !s.startsWith("autre"));
Il est présent dans le même commit. Je le retrouverai, si tu veux

2024-04-04 06:31 UTC, GalloIT commented on anssi-nis2-ui/test/questionnaire/reducerQuestionnaire.spec.ts
> +        valideSecteursActivite(["autreSecteurActivite", "fabrication"]),
Ce test ne reflétait pas la réalité enregistrée dans le formulaire : pour avoir `autreSousSecteurFabrication`, on a forcément coché `fabrication`.

2024-04-04 06:39 UTC, GalloIT commented on anssi-nis2-ui/src/questionnaire/reducerQuestionnaire.ts
Je comprends, quand j'étais à ta place, je disais certainement pareil. Mon oeil s'y est fait. Maintenant, c'est vous qui reprenez, donc faites selon vos goûts.

Ce pattern matching a, en revanche, des arguments factuels en sa faveur. Après quelques années à pratiquer le pattern matching dans plusieurs langages, il réduit énormément la complexité cyclomatique / cognitive. Ici, on réduit les enchainements ` a ? b : c ? d : e` qui sont des sources de bugs et prennent énormément de temps à relire quand on n'a plus la tête dedans. La simplicité apparente des `if` est toujours battue par la complexité de leur imbrication.

Autre aspect intéressant, en remplacement d'un switch, c'est l'utilisation de `exhaustive()` à la place de `otherwise(...)` qui permettrait de ne pas oublier un cas si l'on ajoute une valeur dans nos `type`. Ici, il y a des cas détectés tant que nous n'avons pas supprimé l'ancien code et nous ne pouvons pas en profiter.

Ceci dit : c'est **ton** code, donc on refactore comme tu le souhaites !

2024-04-04 06:40 UTC, GalloIT commented on anssi-nis2-ui/test/questionnaire/reducerUndo.spec.ts
C'est une bonne idée de le découpler. Je m'étais dit la même chose, et ensuite je me suis dit YAGNI

2024-04-04 12:18 UTC, CadiChris commented on anssi-nis2-ui/src/questionnaire/selecteursQuestionnaire.ts
> +    .filter((s) => !s.startsWith("autre"));
Essayons de remplacer le `startsWith` par une fonction du domaine qui existerait déjà. 🙏

2024-04-04 12:18 UTC, CadiChris commented on anssi-nis2-ui/src/questionnaire/quiSupporteUndo.ts
> +type AvecUndo<TEtat extends EtatQuestionnaire> = {
OK pour un retour arrière.

2024-04-04 12:19 UTC, CadiChris commented on anssi-nis2-ui/src/questionnaire/reducerQuestionnaire.ts
OK pour un retour arrière.

2024-04-04 14:07 UTC, GalloIT commented on anssi-nis2-ui/src/Components/Simulateur/Questionnaire.tsx
> +        envoieDonneesFormulaire,
@CadiChris les tests Storybook passent outre le `StrictMode` et les tests passent donc. On peut le laisser si ça te va : le double appel n'arrive qu'en dev.

Toujours aucun soucis à l'enlever pour ma part.

2024-04-04 15:59 UTC, GalloIT commented on anssi-nis2-ui/src/Components/Simulateur/Questionnaire.tsx
> +        envoieDonneesFormulaire,
Le `StrictMode` est supprimé

2024-04-04 16:01 UTC, merged